version: "3.8"

services:
  fdownl:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - storage
      - fdownl_db
    networks:
      - fdownl_net

  storage:
    build:
      context: ./
      dockerfile: ./storage/Dockerfile
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - type: volume
        source: uploads
        target: /Uploads
    depends_on:
      - fdownl_db
    networks:
      - fdownl_net

  fdownl_db:
    image: mysql:8.0
    container_name: fdownl_db
    restart: always
    environment:
      - MYSQL_DATABASE=fdownl
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    networks:
      - fdownl_net

networks:
  fdownl_net:

volumes:
  uploads:
