version: "3.8"

services:
  fdownl:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: fdownl_server
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    restart: always
    ports:
      - "8001:80"
    networks:
      - fdownl_net
    depends_on:
      - storage

  storage:
    build:
      context: ./
      dockerfile: ./docker/storage/Dockerfile
    container_name: fdownl_storage
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    restart: always
    ports:
      - "8002:80"
    volumes:
      - type: volume
        source: uploads
        target: /Uploads
    networks:
      - fdownl_net

networks:
  fdownl_net:

volumes:
  uploads:
