version: "3.5"

services:
  fdownl:
    build: web
    ports:
      - "443:443"
    depends_on:
      - storage
    networks:
      - fdownl-net

  storage:
    build: storage
    volumes:
      - type: volume
        source: uploads
        target: /Uploads
    ports:
      - "3306:3306"
    networks:
      - fdownl-net

networks:
  fdownl-net:
    driver: bridge

volumes:
  uploads:
