name: Website Deploy

on:
  push:
    branches: [ gh_actions ]

jobs:
  deploy:
    runs-on: website-server
    defaults:
      run:
        working-directory: ./src/FDownl
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -c release
   #- name: Launch
   #  run: dotnet bin/release/net5.0/FDownl.dll
