name: Website Deploy

on:
  push:
    branches: [ gh_actions ]

jobs:
  deploy:
    runs-on: website-server
    defaults:
      run:
        working-directory: ./src/FDownl
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -c release
    - name: Backup Old Website
      run: |
        rm -rf ~/old
        if [ -f ~/app ]; then
          mv ~/app ~/old
        fi
    - name: Move Website
      run: mv bin/release/net5.0/publish ~/app
